<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>20190411py15测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">20190411py15测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> 冥鴻</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-05-02 18:04:04</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:26.142761</p>
<p class='attribute'><strong>测试结果 : </strong> 共 91，通过 17，失败 44，错误 30，通过率= 18.68%</p>

<p class='description'>借口测试报告</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 18.68% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 44 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 17 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 91 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='passClass warning'>
    <td>test1_register.RegisterCase</td>
    <td class="text-center">6</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',6)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_1</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_2</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_3</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_4</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_5</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_6' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_register_6</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr class='failClass warning'>
    <td>test2_login.LoginCase</td>
    <td class="text-center">12</td>
    <td class="text-center">11</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',12)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='pt2_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_01</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_02</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_03</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_04</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_05</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_6' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_06</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_07</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_8' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_08</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft2_9' class='none'>
    <td class='failCase'><div class='testcase'>test_login_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse in" align="left">
    <pre>
    
ft2_9: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test2_login.py", line 38, in test_login
    raise e
  File "D:\py-15\作业\week_8\testcases\test2_login.py", line 33, in test_login
    self.assertEqual(expected,resp)
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"登录成功"}' != '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}'
- {"status":1,"code":"10001","data":null,"msg":"登录成功"}
?           ^          ^^^                      ^^^^
+ {"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}
?           ^         ++ ^                      ^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_10' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_10</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_11' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_11</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_12' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_12</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr class='errorClass warning'>
    <td>test3_recharge.RechargeCase</td>
    <td class="text-center">18</td>
    <td class="text-center">0</td>
    <td class="text-center">13</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',18)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>失败</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>失败</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>失败</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}' != 20110


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}' != 20108


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_8' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_8'>失败</button>
    <div id='div_ft3_8' class="collapse in" align="left">
    <pre>
    
ft3_8: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_9' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_9'>失败</button>
    <div id='div_ft3_9' class="collapse in" align="left">
    <pre>
    
ft3_9: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"登录成功"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_10' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_10'>失败</button>
    <div id='div_ft3_10' class="collapse in" align="left">
    <pre>
    
ft3_10: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_11' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_11</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_11'>失败</button>
    <div id='div_ft3_11' class="collapse in" align="left">
    <pre>
    
ft3_11: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_12' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_12</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_12'>失败</button>
    <div id='div_ft3_12' class="collapse in" align="left">
    <pre>
    
ft3_12: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_13' class='none'>
    <td class='failCase'><div class='testcase'>test_recharge_13</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_13'>失败</button>
    <div id='div_ft3_13' class="collapse in" align="left">
    <pre>
    
ft3_13: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 52, in test_recharge
    raise e
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_14</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_14'>错误</button>
    <div id='div_ft3_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_14'>错误</button>
    <div id='div_ft3_14' class="collapse in" align="left">
    <pre>
    
ft3_14: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 35, in test_recharge
    print(member['leaveamount'])
KeyError: 'leaveamount'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_15</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_15'>错误</button>
    <div id='div_ft3_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_15'>错误</button>
    <div id='div_ft3_15' class="collapse in" align="left">
    <pre>
    
ft3_15: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_16</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_16'>错误</button>
    <div id='div_ft3_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_16'>错误</button>
    <div id='div_ft3_16' class="collapse in" align="left">
    <pre>
    
ft3_16: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_17</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_17'>错误</button>
    <div id='div_ft3_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_17'>错误</button>
    <div id='div_ft3_17' class="collapse in" align="left">
    <pre>
    
ft3_17: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_18'>错误</button>
    <div id='div_ft3_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_18'>错误</button>
    <div id='div_ft3_18' class="collapse in" align="left">
    <pre>
    
ft3_18: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test3_recharge.py", line 40, in test_recharge
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test4_withdraw.WithDraw</td>
    <td class="text-center">24</td>
    <td class="text-center">0</td>
    <td class="text-center">14</td>
    <td class="text-center">10</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',24)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>失败</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>失败</button>
    <div id='div_ft4_2' class="collapse in" align="left">
    <pre>
    
ft4_2: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>失败</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}' != 20110


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_4' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_4'>失败</button>
    <div id='div_ft4_4' class="collapse in" align="left">
    <pre>
    
ft4_4: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_5' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_5'>失败</button>
    <div id='div_ft4_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_5'>失败</button>
    <div id='div_ft4_5' class="collapse in" align="left">
    <pre>
    
ft4_5: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_6' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_6'>失败</button>
    <div id='div_ft4_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_6'>失败</button>
    <div id='div_ft4_6' class="collapse in" align="left">
    <pre>
    
ft4_6: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}' != 20108


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_7' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_7'>失败</button>
    <div id='div_ft4_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_7'>失败</button>
    <div id='div_ft4_7' class="collapse in" align="left">
    <pre>
    
ft4_7: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_8' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_8'>失败</button>
    <div id='div_ft4_8' class="collapse in" align="left">
    <pre>
    
ft4_8: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_9' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_9'>失败</button>
    <div id='div_ft4_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_9'>失败</button>
    <div id='div_ft4_9' class="collapse in" align="left">
    <pre>
    
ft4_9: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"登录成功"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_10' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_10'>失败</button>
    <div id='div_ft4_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_10'>失败</button>
    <div id='div_ft4_10' class="collapse in" align="left">
    <pre>
    
ft4_10: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_11' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_11</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_11'>失败</button>
    <div id='div_ft4_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_11'>失败</button>
    <div id='div_ft4_11' class="collapse in" align="left">
    <pre>
    
ft4_11: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_12' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_12</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_12'>失败</button>
    <div id='div_ft4_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_12'>失败</button>
    <div id='div_ft4_12' class="collapse in" align="left">
    <pre>
    
ft4_12: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_13' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_13</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_13'>失败</button>
    <div id='div_ft4_13' class="collapse in" align="left">
    <pre>
    
ft4_13: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_14</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_14'>错误</button>
    <div id='div_ft4_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_14'>错误</button>
    <div id='div_ft4_14' class="collapse in" align="left">
    <pre>
    
ft4_14: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_15</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_15'>错误</button>
    <div id='div_ft4_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_15'>错误</button>
    <div id='div_ft4_15' class="collapse in" align="left">
    <pre>
    
ft4_15: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_16</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_16'>错误</button>
    <div id='div_ft4_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_16'>错误</button>
    <div id='div_ft4_16' class="collapse in" align="left">
    <pre>
    
ft4_16: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_17</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_17'>错误</button>
    <div id='div_ft4_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_17'>错误</button>
    <div id='div_ft4_17' class="collapse in" align="left">
    <pre>
    
ft4_17: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_18'>错误</button>
    <div id='div_ft4_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_18'>错误</button>
    <div id='div_ft4_18' class="collapse in" align="left">
    <pre>
    
ft4_18: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_19' class='none'>
    <td class='failCase'><div class='testcase'>test_withdraw_19</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_19'>失败</button>
    <div id='div_ft4_19' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_19'>失败</button>
    <div id='div_ft4_19' class="collapse in" align="left">
    <pre>
    
ft4_19: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 35, in test_withdraw
    raise e
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_20' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_20</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_20'>错误</button>
    <div id='div_ft4_20' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_20'>错误</button>
    <div id='div_ft4_20' class="collapse in" align="left">
    <pre>
    
ft4_20: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_21' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_21</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_21' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_21'>错误</button>
    <div id='div_ft4_21' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_21' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_21'>错误</button>
    <div id='div_ft4_21' class="collapse in" align="left">
    <pre>
    
ft4_21: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_22' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_22</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_22'>错误</button>
    <div id='div_ft4_22' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_22'>错误</button>
    <div id='div_ft4_22' class="collapse in" align="left">
    <pre>
    
ft4_22: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_23' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_23</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_23' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_23'>错误</button>
    <div id='div_ft4_23' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_23' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_23'>错误</button>
    <div id='div_ft4_23' class="collapse in" align="left">
    <pre>
    
ft4_23: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_24' class='none'>
    <td class='errorCase'><div class='testcase'>test_withdraw_24</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_24'>错误</button>
    <div id='div_ft4_24' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_24'>错误</button>
    <div id='div_ft4_24' class="collapse in" align="left">
    <pre>
    
ft4_24: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test4_withdraw.py", line 30, in test_withdraw
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test5_invest.InvestCase</td>
    <td class="text-center">31</td>
    <td class="text-center">0</td>
    <td class="text-center">16</td>
    <td class="text-center">15</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',31)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='ft5_1' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_1'>失败</button>
    <div id='div_ft5_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_1'>失败</button>
    <div id='div_ft5_1' class="collapse in" align="left">
    <pre>
    
ft5_1: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_2' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_2'>失败</button>
    <div id='div_ft5_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_2'>失败</button>
    <div id='div_ft5_2' class="collapse in" align="left">
    <pre>
    
ft5_2: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20109","data":null,"msg":"手机号码格式不正确"}' != 20109


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_3' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_3'>失败</button>
    <div id='div_ft5_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_3'>失败</button>
    <div id='div_ft5_3' class="collapse in" align="left">
    <pre>
    
ft5_3: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20110","data":null,"msg":"手机号码已被注册"}' != 20110


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_4' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_4'>失败</button>
    <div id='div_ft5_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_4'>失败</button>
    <div id='div_ft5_4' class="collapse in" align="left">
    <pre>
    
ft5_4: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_5' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_5'>失败</button>
    <div id='div_ft5_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_5'>失败</button>
    <div id='div_ft5_5' class="collapse in" align="left">
    <pre>
    
ft5_5: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_6' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_6'>失败</button>
    <div id='div_ft5_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_6'>失败</button>
    <div id='div_ft5_6' class="collapse in" align="left">
    <pre>
    
ft5_6: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20108","data":null,"msg":"密码长度必须为6~18"}' != 20108


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_7' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_7'>失败</button>
    <div id='div_ft5_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_7'>失败</button>
    <div id='div_ft5_7' class="collapse in" align="left">
    <pre>
    
ft5_7: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_8' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_8'>失败</button>
    <div id='div_ft5_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_8'>失败</button>
    <div id='div_ft5_8' class="collapse in" align="left">
    <pre>
    
ft5_8: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"密码不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_9' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_9'>失败</button>
    <div id='div_ft5_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_9'>失败</button>
    <div id='div_ft5_9' class="collapse in" align="left">
    <pre>
    
ft5_9: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":1,"code":"10001","data":null,"msg":"登录成功"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_10' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_10'>失败</button>
    <div id='div_ft5_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_10'>失败</button>
    <div id='div_ft5_10' class="collapse in" align="left">
    <pre>
    
ft5_10: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_11' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_11</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_11'>失败</button>
    <div id='div_ft5_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_11'>失败</button>
    <div id='div_ft5_11' class="collapse in" align="left">
    <pre>
    
ft5_11: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20111","data":null,"msg":"用户名或密码错误"}' != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_12' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_12</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_12'>失败</button>
    <div id='div_ft5_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_12'>失败</button>
    <div id='div_ft5_12' class="collapse in" align="left">
    <pre>
    
ft5_12: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: '{"status":0,"code":"20103","data":null,"msg":"手机号不能为空"}' != 20103


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_13' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_13</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_13'>失败</button>
    <div id='div_ft5_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_13'>失败</button>
    <div id='div_ft5_13' class="collapse in" align="left">
    <pre>
    
ft5_13: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_14</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_14'>错误</button>
    <div id='div_ft5_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_14'>错误</button>
    <div id='div_ft5_14' class="collapse in" align="left">
    <pre>
    
ft5_14: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_15</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_15'>错误</button>
    <div id='div_ft5_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_15'>错误</button>
    <div id='div_ft5_15' class="collapse in" align="left">
    <pre>
    
ft5_15: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_16</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_16'>错误</button>
    <div id='div_ft5_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_16'>错误</button>
    <div id='div_ft5_16' class="collapse in" align="left">
    <pre>
    
ft5_16: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_17</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_17'>错误</button>
    <div id='div_ft5_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_17'>错误</button>
    <div id='div_ft5_17' class="collapse in" align="left">
    <pre>
    
ft5_17: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_18'>错误</button>
    <div id='div_ft5_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_18'>错误</button>
    <div id='div_ft5_18' class="collapse in" align="left">
    <pre>
    
ft5_18: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_19' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_19</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_19'>失败</button>
    <div id='div_ft5_19' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_19'>失败</button>
    <div id='div_ft5_19' class="collapse in" align="left">
    <pre>
    
ft5_19: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_20' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_20</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_20'>错误</button>
    <div id='div_ft5_20' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_20'>错误</button>
    <div id='div_ft5_20' class="collapse in" align="left">
    <pre>
    
ft5_20: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_21' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_21</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_21' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_21'>错误</button>
    <div id='div_ft5_21' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_21' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_21'>错误</button>
    <div id='div_ft5_21' class="collapse in" align="left">
    <pre>
    
ft5_21: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_22' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_22</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_22'>错误</button>
    <div id='div_ft5_22' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_22'>错误</button>
    <div id='div_ft5_22' class="collapse in" align="left">
    <pre>
    
ft5_22: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_23' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_23</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_23' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_23'>错误</button>
    <div id='div_ft5_23' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_23' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_23'>错误</button>
    <div id='div_ft5_23' class="collapse in" align="left">
    <pre>
    
ft5_23: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_24' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_24</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_24'>错误</button>
    <div id='div_ft5_24' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_24'>错误</button>
    <div id='div_ft5_24' class="collapse in" align="left">
    <pre>
    
ft5_24: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_25' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_25</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_25' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_25'>失败</button>
    <div id='div_ft5_25' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_25' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_25'>失败</button>
    <div id='div_ft5_25' class="collapse in" align="left">
    <pre>
    
ft5_25: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_26' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_26</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_26' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_26'>错误</button>
    <div id='div_ft5_26' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_26' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_26'>错误</button>
    <div id='div_ft5_26' class="collapse in" align="left">
    <pre>
    
ft5_26: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_27' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_27</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_27' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_27'>错误</button>
    <div id='div_ft5_27' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_27' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_27'>错误</button>
    <div id='div_ft5_27' class="collapse in" align="left">
    <pre>
    
ft5_27: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 31, in test_invest
    data = self.context.replace(json.dumps(data))
  File "D:\py-15\作业\week_8\common\context.py", line 25, in replace
    data = re.sub(self.p, v, data, count=1)  # 替换
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 227, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_28' class='none'>
    <td class='failCase'><div class='testcase'>test_invest_28</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_28' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_28'>失败</button>
    <div id='div_ft5_28' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_28' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_28'>失败</button>
    <div id='div_ft5_28' class="collapse in" align="left">
    <pre>
    
ft5_28: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 64, in test_invest
    raise e
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 44, in test_invest
    self.assertEqual(expected,int(resp2))
AssertionError: 10001 != 20111


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_29' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_29</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_29' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_29'>错误</button>
    <div id='div_ft5_29' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_29' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_29'>错误</button>
    <div id='div_ft5_29' class="collapse in" align="left">
    <pre>
    
ft5_29: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 31, in test_invest
    data = self.context.replace(json.dumps(data))
  File "D:\py-15\作业\week_8\common\context.py", line 25, in replace
    data = re.sub(self.p, v, data, count=1)  # 替换
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 227, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_30' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_30</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_30' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_30'>错误</button>
    <div id='div_ft5_30' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_30' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_30'>错误</button>
    <div id='div_ft5_30' class="collapse in" align="left">
    <pre>
    
ft5_30: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 31, in test_invest
    data = self.context.replace(json.dumps(data))
  File "D:\py-15\作业\week_8\common\context.py", line 25, in replace
    data = re.sub(self.p, v, data, count=1)  # 替换
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 227, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_31' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_31</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_31' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_31'>错误</button>
    <div id='div_ft5_31' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_31' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_31'>错误</button>
    <div id='div_ft5_31' class="collapse in" align="left">
    <pre>
    
ft5_31: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py-15\作业\week_8\testcases\test5_invest.py", line 31, in test_invest
    data = self.context.replace(json.dumps(data))
  File "D:\py-15\作业\week_8\common\context.py", line 25, in replace
    data = re.sub(self.p, v, data, count=1)  # 替换
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\sre_parse.py", line 227, in __init__
    string = str(string, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>91</td>
    <td>17</td>
    <td>44</td>
    <td>30</td>
    <td>通过率：18.68%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
